NGINX_BASE_PATH: "/etc/nginx"
NGINX_SITE_AVAILABLE_PATH: "{{ NGINX_BASE_PATH }}/sites-available"
NGINX_SITE_ENABLED_PATH: "{{ NGINX_BASE_PATH }}/sites-enabled"
NGINX_CONF_PATH: "{{ NGINX_BASE_PATH }}/conf.d"
NGINX_USER: www-data
NGINX_GROUP: www-data
