---
- name: Setup passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Disable password authentication for root
  lineinfile:
    path: "{{ SSH_CONF_FILE }}"
    state: present
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"

- name: Disable password authentication
  lineinfile:
    path: "{{ SSH_CONF_FILE }}"
    state: present
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: Disable X11 forwarding
  lineinfile:
    path: "{{ SSH_CONF_FILE }}"
    state: present
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding no"

- name: Disable MaxAuthTries
  lineinfile:
    path: "{{ SSH_CONF_FILE }}"
    state: present
    regexp: "^#?MaxAuthTries"
    line: "MaxAuthTries 2"

- name: Disable AllowTcpForwarding
  lineinfile:
    path: "{{ SSH_CONF_FILE }}"
    state: present
    regexp: "^#?AllowTcpForwarding"
    line: "AllowTcpForwarding no"

- name: Disable AllowAgentForwarding
  lineinfile:
    path: "{{ SSH_CONF_FILE }}"
    state: present
    regexp: "^#?AllowAgentForwarding"
    line: "AllowAgentForwarding no"

- name: Disable X11 forwarding
  lineinfile:
    path: "{{ SSH_CONF_FILE }}"
    state: present
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding no"

- name: Change SSH port
  lineinfile:
    path: "{{ SSH_CONF_FILE }}"
    state: present
    regexp: "^#?Port"
    line: "Port {{ vault_vars.CUSTOM_SSH_PORT }}"

- name: Reload SSH service to apply changes
  service:
    name: sshd
    state: reloaded
