---
- name: UFW - Enable and deny by default
  community.general.ufw:
    state: enabled
    default: deny

- name: Allow SSH through UFW
  ufw:
    rule: allow
    port: "{{ vault_vars.CUSTOM_SSH_PORT }}"
    proto: tcp

- name: UFW - Allow Nginx (HTTP)
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: UFW - Allow Nginx (HTTPS)
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: UFW - Reload rules
  community.general.ufw:
    state: reloaded
