- name: Copy the service template to the server
  template:
    src: service.j2
    dest: /etc/systemd/system/{{ service_name }}.service
  notify: Reload systemd

- name: Enable and start the service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
