---
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ created_username }}"
    state: present
    groups: # Empty by default
      - www-data
      - sudo
    append: true
    create_home: true

- name: Set authorized key for remote user
  ansible.posix.authorized_key:
    user: "{{ created_username }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/hetzner.pub') }}"

- name: Set allowed users
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: 'AllowUsers {{ allowed_users | join(" ") }}'
    state: present
