---
- name: Add Nginx configuration file from template
  template:
    src: web-server.j2
    dest: "{{ NGINX_SITE_AVAILABLE_PATH }}/{{ domain }}.conf"

- name: Create a symlink to sites-enabled
  file:
    src: "{{ NGINX_SITE_AVAILABLE_PATH }}/{{ domain }}.conf"
    dest: "{{ NGINX_SITE_ENABLED_PATH }}/{{ domain }}.conf"
    state: link
    force: yes
  notify: Reload Nginx
