---
- name: Add Nginx configuration file from template
  template:
    src: nginx.conf.j2
    dest: "{{ NGINX_SITE_AVAILABLE_PATH }}/{{ domain }}.conf"
  vars:
    domain: "{{ domain }}"
    local_port: "{{ local_port }}"
    nginx_user: "{{ NGINX_USER }}"

- name: Create a symlink to sites-enabled
  file:
    src: "{{ NGINX_SITE_AVAILABLE_PATH }}/{{ domain }}.conf"
    dest: "{{ NGINX_SITE_ENABLED_PATH }}/{{ domain }}.conf"
    state: link
    force: yes
  notify: Reload Nginx
